int qsMain();
int qsHello();
int qsGetline(char *line, int nline);
int qsValidate(char *line, int nline, double *a, double *b, double *c);
int qsSolve(double a, double b, double c, double *x1, double *x2);
int qsErrors();
int qsResults();
int qsPutline(char *line, int nline);
int qsLogEnable();
int qsLog();
int qsHelp();
